log_level: DEBUG

modbus: 
  host: 192.168.178.95
  port: 502
  registers:
    status: 
      address: 104
      length: 1
    total_energy:
      address: 218
      length: 2
    charged_energy:
      address: 716
      length: 2
    idtag_1:
      address: 720
      length: 2
    idtag_2:
      address: 722
      length: 2
    idtag_3:
      address: 724
      length: 2
    idtag_4:
      address: 726
      length: 2
    idtag_5:
      address: 728
      length: 2

signal:
  host: 192.168.178.23
  port: 4126
  own_number: "+4916090638879"
  send_number: "+4916090638879"
  check_frequency: 10
